RN50:
  counts: [3, 4, 6, 3]
  vision_width: 64
  output_width: 7
  embed_dim: 1024
  context_length: 77
  vocab_size: 49408
  transformer_width: 512
  transformer_layers: 12

RN101:
  counts: [3, 4, 23, 3]
  vision_width: 64
  output_width: 7
  embed_dim: 512
  context_length: 77
  vocab_size: 49408
  transformer_width: 512
  transformer_layers: 12

RN50x4: 
  counts: [6, 8, 18, 8]
  vision_width: 80
  output_width: 9
  embed_dim: 640
  context_length: 77
  vocab_size: 49408
  transformer_width: 640
  transformer_layers: 12

RN50x16:
  counts: [6, 8, 18, 8]
  vision_width: 96
  output_width: 12
  embed_dim: 768
  context_length: 77
  vocab_size: 49408
  transformer_width: 768
  transformer_layers: 12

RN50x64:
  counts: [3, 15, 36, 10]
  vision_width: 128
  output_width: 14
  embed_dim: 1024
  context_length: 77
  vocab_size: 49408
  transformer_width: 1024
  transformer_layers: 12

ViT-B/32:
  vision_width: 768
  vision_layers: 12
  vision_patch_size: 32
  grid_size: 7
  embed_dim: 512
  context_length: 77
  vocab_size: 49408
  transformer_width: 512
  transformer_layers: 12

ViT-B/16:
  vision_width: 768
  vision_layers: 12
  vision_patch_size: 16
  grid_size: 14
  embed_dim: 512
  context_length: 77
  vocab_size: 49408
  transformer_width: 512
  transformer_layers: 12

ViT-L/14:
  vision_width: 1024
  vision_layers: 24
  vision_patch_size: 14
  grid_size: 16
  embed_dim: 768
  context_length: 77
  vocab_size: 49408
  transformer_width: 768
  transformer_layers: 12

ViT-L/14@336px:
  vision_width: 1024
  vision_layers: 24
  vision_patch_size: 14
  grid_size: 24
  embed_dim: 768
  context_length: 77
  vocab_size: 49408
  transformer_width: 768
  transformer_layers: 12

