train:
  epoch: 40
  batch_size: 32
  ckpt_save_path: /root/autodl-tmp/checkpoint/
  ckpt: None
  scaler: None
  log_dir: /root/tf-logs

optimizer:
  name: Adam
  lr: 1e-4
  betas: (0.9,0.98)
  eps: 1e-6
  weight_decay: 0.2

# lr_scheduler: 
#   name: CosineAnnealingLR
#   T_max: 15
#   eta_min: 0.00001

test:
  batch_size: 256
  ckpt: /root/autodl-tmp/checkpoint/checkpoint_epoch16.pth


dataset:
  train_json_path: /root/CLIP1/json_data/new.json
  train_image_path: /root/autodl-tmp/q-instruct-images
  valid_input_filename: None
  test_json_path: /root/autodl-tmp/test/json/koniq.json
  test_image_path: /root/autodl-tmp/test/koniq10k
  n_px: 224


# [test_json_path, test_image_path]
# [/root/autodl-tmp/test/json/kadid.json, /root/autodl-tmp/test/kadid10k]
# [/root/autodl-tmp/test/json/agi.json, /root/autodl-tmp/test/AGIQA-3K]
# [/root/autodl-tmp/test/json/cgi.json, /root/autodl-tmp/test/CGIQA-6K]
# [/root/autodl-tmp/test/json/flive.json, /root/autodl-tmp/test/flive]
# [/root/autodl-tmp/test/json/koniq.json, /root/autodl-tmp/test/koniq10k]
# [/root/autodl-tmp/test/json/livec.json, /root/autodl-tmp/test/livec]
# [/root/autodl-tmp/test/json/spaq.json, /root/autodl-tmp/test/SPAQ/TestImage]


